import { Product } from './product.interface';

let id: number = 0;
export const products: Product[] = [
  {
    id: ++id,
    img: '/images/recipes/cookies.jpg',
    title: 'Classic Cookies',
    price: 0.5,
    quantity: "Per piece",
  },
  {
    id: ++id,
    img: '/images/recipes/chocolate-cookies.jpg',
    title: 'Chocolate Cookies',
    price: 1.0,
    quantity: "Per piece",
  },
  {
    id: ++id,
    img: '/images/recipes/berryjpg.jpg',
    title: 'Blur Berry Cookies',
    price: 1.0,
    quantity: "Per piece",
  },
  {
    id: ++id,
    img: '/images/recipes/pistachio-cookies.jpg',
    title: 'pistachio Cookies',
    price: 1.0,
    quantity: "Per piece",
  },
  {
    id: ++id,
    img: '/images/recipes/cinnamon-cookies.jpg',
    title: 'Cinnamon Cookies',
    price: 0.5,
    quantity: "Per piece",
  },
  {
    id: ++id,
    img: '/images/recipes/pancakes.jpg',
    title: 'Fluffy Pancakes',
    price: 1.0,
    quantity: "6 piece",
  },
  {
    id: ++id,
    img: '/images/recipes/muffins.jpg',
    title: 'chocolate Muffins',
    price: 0.5,
    quantity: "Per piece",
  },
  {
    id: ++id,
    img: '/images/recipes/red-velvet-cupcake.jpg',
    title: 'Red Velvet Cupcake',
    price: 0.5,
    quantity: "Per piece",
  },
  {
    id: ++id,
    img: '/images/recipes/cinnamon-roll.jpg',
    title: 'Cinnamon Roll',
    price: 1.0,
    quantity: "Per piece",
  },
  {
    id: ++id,
    img: '/images/recipes/donut.jpg',
    title: 'Chocolate Donut',
    price: 1.0,
    quantity: "Per piece",
  },
  {
    id: ++id,
    img: '/images/recipes/chocolate-cake.jpg',
    title: 'Chocolate Cake',
    price: 5.0,
    quantity: "Per 6 piece",
  },
  {
    id: ++id,
    img: '/images/recipes/red-velvet-cake.jpg',
    title: 'Red Velvet Cake',
    price: 7.0,
    quantity: "Per 6 piece",
  },
  {
    id: ++id,
    img: '/images/recipes/cheescake.jpg',
    title: 'Cheesecake',
    price: 1.5,
    quantity: "Per piece",
  },
  {
    id: ++id,
    img: '/images/recipes/lunchbox-cake.jpg',
    title: 'Lunchbox Cake',
    price: 4.0,
    quantity: "Per piece",
  },
  {
    id: ++id,
    img: '/images/recipes/honeycomb-bread.jpg',
    title: 'Honeycomb Bread',
    price: 3.0,
    quantity: "Per piece",
  },
]
